/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import proyectoclinica.Conexion;
import proyectoclinica.HeaderTable;
import proyectoclinica.raza;

/**
 *
 * @author Male
 */
public class FrameRaza extends javax.swing.JFrame {

    
    raza rz;
    DefaultTableModel model;
    Conexion cnx=new Conexion();
    public FrameRaza() {
         rz=new raza();
         
        initComponents();
          rz.Buscar(tableraza ,"");
          this.repintarHeaderTabla();
    }
    private void repintarHeaderTabla(){
        JTableHeader jtableHeader = tableraza.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderTable());
        tableraza.setTableHeader(jtableHeader);
    }
    public void Limpiar ()
    {            
        idrz.setText("");
        desrz.setText("");
    }
      public void Bloquear()
    {
        idrz.setEnabled(false);
        desrz.setEnabled(false);
   
    }
      
    public void Desbloquear ()
    {
        idrz.setEnabled(true);
        desrz.setEnabled(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tableraza = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desrz = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        idrz = new javax.swing.JTextPane();
        jButton6 = new javax.swing.JButton();
        JBLIMPIAR = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        JBSELECCIONAR = new javax.swing.JButton();
        jButtonGUARDAR = new javax.swing.JButton();
        jButtonNUEVO = new javax.swing.JButton();
        JBMODIFICAR = new javax.swing.JButton();
        JBMOSTRAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jidTipoanimal = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableraza.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tableraza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableraza.setGridColor(new java.awt.Color(204, 204, 255));
        tableraza.setSelectionBackground(new java.awt.Color(204, 153, 0));
        jScrollPane3.setViewportView(tableraza);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 610, 160));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel4.setText("NOMBRE RAZA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel3.setText("ID TIPOANIMAL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jScrollPane2.setViewportView(desrz);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 190, 30));

        jScrollPane1.setViewportView(idrz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 150, 30));

        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 100, 30));

        JBLIMPIAR.setText("LIMPIAR");
        JBLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLIMPIARActionPerformed(evt);
            }
        });
        getContentPane().add(JBLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 90, 30));

        JBEliminar.setText("ELIMINAR");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(JBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 90, 30));

        JBSELECCIONAR.setText("SELECCIONAR");
        JBSELECCIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSELECCIONARActionPerformed(evt);
            }
        });
        getContentPane().add(JBSELECCIONAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 120, 30));

        jButtonGUARDAR.setText("GUARDAR");
        jButtonGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, 30));

        jButtonNUEVO.setText("NUEVO");
        jButtonNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        JBMODIFICAR.setText("MODIFICAR");
        JBMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(JBMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 110, 30));

        JBMOSTRAR.setBackground(new java.awt.Color(255, 255, 255));
        JBMOSTRAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JBMOSTRAR.setText("MOSTRAR");
        JBMOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMOSTRARActionPerformed(evt);
            }
        });
        getContentPane().add(JBMOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 130, -1));

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 0, 48)); // NOI18N
        jLabel2.setText("RAZA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel5.setText("ID RAZA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jScrollPane4.setViewportView(jidTipoanimal);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNUEVOActionPerformed
     Desbloquear();
        jButtonNUEVO.setEnabled(true);
        jButtonGUARDAR.setEnabled(true);
        JBMODIFICAR.setEnabled(false);
        JBEliminar.setEnabled(false);
        JBLIMPIAR.setEnabled(true);
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNUEVOActionPerformed

    private void jButtonGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGUARDARActionPerformed
    rz.Insertar(Integer.parseInt(idrz.getText()),Integer.parseInt(jidTipoanimal.getText()), desrz.getText());
      rz.Buscar(tableraza ,"");
      Bloquear();
        Limpiar();
     
      
    }//GEN-LAST:event_jButtonGUARDARActionPerformed

    private void JBSELECCIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSELECCIONARActionPerformed
 int fmod = tableraza.getSelectedRow();
       if (fmod >= 0) {
           idrz.setText(tableraza.getValueAt(fmod, 0).toString());
           desrz.setText(tableraza.getValueAt(fmod, 1).toString());
          
            
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ");
        } 
       Desbloquear();
      JBSELECCIONAR.setEnabled(true);
      JBEliminar.setEnabled(true);
      JBLIMPIAR.setEnabled(true);
      jButtonGUARDAR.setEnabled(false);
      jButtonNUEVO.setEnabled(false);
      JBMODIFICAR.setEnabled(true);

    }//GEN-LAST:event_JBSELECCIONARActionPerformed

    private void JBLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLIMPIARActionPerformed
     Limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_JBLIMPIARActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
 // TODO add your handling code here:
        rz.Eliminar(Integer.parseInt(idrz.getText()),desrz.getText());
        rz.Buscar(tableraza,"");

        JOptionPane.showMessageDialog(rootPane, "Los datos se han ELIMINADO con exito");
       
        Limpiar();        // TODO add your handling code here:
        Bloquear();
        jButtonNUEVO.setEnabled(true);
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void JBMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMODIFICARActionPerformed
    rz.Actualizar(Integer.parseInt(idrz.getText()), desrz.getText());
      rz.Buscar(tableraza ,"");
      JOptionPane.showMessageDialog(rootPane, "Los datos se han actualizado con exito");
      Bloquear();
        Limpiar();
         rz.Buscar(tableraza, "");
        jButtonNUEVO.setEnabled(true);
    }//GEN-LAST:event_JBMODIFICARActionPerformed

    private void JBMOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMOSTRARActionPerformed
      rz.Buscar(tableraza ,"");  
      JBMOSTRAR.setEnabled(false);
    }//GEN-LAST:event_JBMOSTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRaza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRaza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEliminar;
    private javax.swing.JButton JBLIMPIAR;
    private javax.swing.JButton JBMODIFICAR;
    private javax.swing.JButton JBMOSTRAR;
    private javax.swing.JButton JBSELECCIONAR;
    private javax.swing.JTextPane desrz;
    private javax.swing.JTextPane idrz;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonGUARDAR;
    private javax.swing.JButton jButtonNUEVO;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jidTipoanimal;
    private javax.swing.JTable tableraza;
    // End of variables declaration//GEN-END:variables
}
