/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import proyectoclinica.Animal;
import proyectoclinica.Conexion;
import proyectoclinica.HeaderTable;
import proyectoclinica.Propietario;
import proyectoclinica.raza;

/**
 *
 * @author Male
 */
public class FrameAnimal extends javax.swing.JFrame {

    /**
     * Creates new form FrameAnimal
     */
    Animal an;
    raza rz;
    Propietario pro;
    
    DefaultTableModel model;
    
    Conexion cnx=new Conexion();
    public FrameAnimal() {
         an=new Animal();
         rz= new raza();
         pro= new Propietario();
        
        initComponents();
        // rz.ListarRaza(desplegable);
         this.repintarHeaderTablaan();
        this.repintarHeaderTablapro();
    }
    private void repintarHeaderTablaan(){
        JTableHeader jtableHeader = tablean.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderTable());
        tablean.setTableHeader(jtableHeader);
    }
        private void repintarHeaderTablapro(){
        JTableHeader jtableHeader = tablepro.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderTable());
       tablepro.setTableHeader(jtableHeader);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        JTidanimal = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        JTfechaAnimal = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        JTnombreAnimal = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jcolor = new javax.swing.JTextPane();
        idpro = new javax.swing.JScrollPane();
        jtidpropietario = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cipro = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbbuscar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JBAGREGAR = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablean = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablepro = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jraza = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTipoan = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel13.setText("Raza:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jScrollPane9.setViewportView(JTidanimal);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 160, -1));

        jScrollPane8.setViewportView(JTfechaAnimal);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 150, -1));

        jScrollPane7.setViewportView(JTnombreAnimal);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 140, -1));

        jScrollPane6.setViewportView(jcolor);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 140, -1));

        idpro.setViewportView(jtidpropietario);

        getContentPane().add(idpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 170, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel11.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel10.setText("Color");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 40));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel9.setText("ID_Animal:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 170, 20));

        jScrollPane2.setViewportView(cipro);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel8.setText("Nombre Animal:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, 50));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel7.setText("CI Propietario:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        jbbuscar.setText("buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, 110, 40));

        JBAGREGAR.setText("AGREGAR");
        JBAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAGREGARActionPerformed(evt);
            }
        });
        getContentPane().add(JBAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 120, 30));

        jButton2.setText("MOSTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 140, 40));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 100, 40));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel6.setText("idpropietario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 60));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("ANIMAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 270, -1));

        tablean.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablean);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 382, 530, 190));

        tablepro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablepro);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 520, 210));

        jButton3.setText("AÑADIR HISTORIAL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        jScrollPane4.setViewportView(jraza);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 120, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("Tipo Animal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jScrollPane5.setViewportView(jTipoan);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        an.Insertar(Integer.parseInt(JTidanimal.getText()), JTnombreAnimal.getText(),jcolor.getText(), JTfechaAnimal.getText(), Integer.parseInt(cipro.getText()),Integer.parseInt(jraza.getText()),Integer.parseInt(jTipoan.getText()));//desplegable.getItemAt(desplegable.getSelectedIndex()).GetIdraza());    
        an.Buscar(tablean, "");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
an.Buscar(tablean, "");     
pro.Buscar(tablepro, "");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
//pro.Buscaridpro(tablepro,cipro.getText());
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void JBAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAGREGARActionPerformed
 int fmod = tablepro.getSelectedRow();
       if (fmod >= 0) {
          jtidpropietario.setText(tablepro.getValueAt(fmod, 0).toString());
          
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_JBAGREGARActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 FrameHistorial his = new FrameHistorial();
 his.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAGREGAR;
    private javax.swing.JTextPane JTfechaAnimal;
    private javax.swing.JTextPane JTidanimal;
    private javax.swing.JTextPane JTnombreAnimal;
    private javax.swing.JTextPane cipro;
    private javax.swing.JScrollPane idpro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTipoan;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JTextPane jcolor;
    private javax.swing.JTextPane jraza;
    private javax.swing.JTextPane jtidpropietario;
    private javax.swing.JTable tablean;
    private javax.swing.JTable tablepro;
    // End of variables declaration//GEN-END:variables
}
