/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import proyectoclinica.PlaceHolder;
import proyectoclinica.usuario;

public class Framelogin extends javax.swing.JFrame {

    private final usuario usuario;
    public Framelogin() {
        initComponents();
         usuario=new usuario();
       this.inicioEnConstructor();
      // this.ingresarAlSistema();
    }
     private void inicioEnConstructor(){
        if(!usuario.esConexionNull()){
            this.setLocationRelativeTo(null);
            jTextFieldusername.requestFocus();
            
            PlaceHolder placeholder = new PlaceHolder("Nombre usuario", jTextFieldusername, new Color(0,0,0));
                        placeholder = new PlaceHolder("Contraseña", jPassword, new Color(0,0,0));
                       
           // this.mostrarAlertaBloqMayusActivado();
        }else
            System.exit(0);  //si hubiera problemas con la conexion a la base de datos, entonces se va cerrar el programma
    }
   
private void ingresarAlSistema(){
        //La existencia de un usuario en la BD se verifica en el JTUsuario, ni bien se da ENTER lo verifica y el cursor no llega al campo de contraseña si el usuario no existe
        if(!jPassword.getText().isEmpty() && !jTextFieldusername.getText().isEmpty()){
            String [] usuarioLogueado = usuario.validarIngresoAlSistema(jTextFieldusername.getText(), jPassword.getText());
            
            if(usuarioLogueado != null){
                
                Frameprincipal form = new Frameprincipal();
                /*FormPrincipal.jLabelIdMedico.setText(usuarioLogueado[0]);
                FormPrincipal.jLabelNombreMedico.setText(usuarioLogueado[1]);
                
                form.mostrarBotonesSegunTipoUsuario( usuarioLogueado[2].equals("S") ); //si es secretaria.*/
                form.setVisible(true);
            }else
                JOptionPane.showMessageDialog(null, "Estos credenciales no existen!\nRevise bien y vuelva a intentarlo.", "Información", JOptionPane.WARNING_MESSAGE);
            
        }else if(jTextFieldusername.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "LOS CAMPOS ESTÁN VACÍOS !!!", "Mensaje", JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(rootPane, "INTRODUZCA SU CONTRASEÑA !!!", "Mensaje", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldusername.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jTextFieldusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/veterinario (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 140, 150));

        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 130, 30));

        jPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPassword.setText("jPasswordField1");
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 140, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/fondo usuario.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
      //  this.ingresarAlSistema();
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jTextFieldusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldusernameActionPerformed
        // TODO add your handling code here:
       // this.ingresarAlSistema();
    }//GEN-LAST:event_jTextFieldusernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       this.ingresarAlSistema();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framelogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framelogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldusername;
    // End of variables declaration//GEN-END:variables
}
