/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import proyectoclinica.Conexion;
import proyectoclinica.HeaderTable;
import proyectoclinica.Propietario;

/**
 *
 * @author Male
 */
public class FramePropietario extends javax.swing.JFrame {

    /**
     * Creates new form FramePropietario
     */
   Propietario pro;
    DefaultTableModel model;
    Conexion cnx= new Conexion();
    public FramePropietario(){
    
    pro= new Propietario();
        initComponents();
        Bloquear();
        this.repintarHeaderTabla();
    }
    private void repintarHeaderTabla(){
        JTableHeader jtableHeader = jTable1.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderTable());
        jTable1.setTableHeader(jtableHeader);
    }
     public void Limpiar ()
    {            
        CARNET.setText("");
        NOMBRE.setText("");
        APELLIDO.setText("");
        CELULAR.setText("");
        DIRECCION.setText("");
        correo.setText("");
    }
      public void Bloquear()
    {
        CARNET.setEnabled(false);
        correo.setEnabled(false);
        NOMBRE.setEnabled(false);
         APELLIDO.setEnabled(false);
         CELULAR.setEnabled(false);
         DIRECCION.setEnabled(false);
    }
      
    public void Desbloquear ()
    {
         CARNET.setEnabled(true);
        correo.setEnabled(true);
        NOMBRE.setEnabled(true);
         APELLIDO.setEnabled(true);
         CELULAR.setEnabled(true);
         DIRECCION.setEnabled(true);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        DIRECCION = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        CELULAR = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        APELLIDO = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        NOMBRE = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        CARNET = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        eliminarjt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        JBGUARDAR = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MOSTRAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        JBSELECCIONAR = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        JBLIMPIAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        correo = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane8.setViewportView(DIRECCION);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 210, -1));

        jScrollPane7.setViewportView(CELULAR);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 160, 30));

        jScrollPane5.setViewportView(APELLIDO);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 190, 30));

        jScrollPane4.setViewportView(NOMBRE);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 160, 30));

        jScrollPane2.setViewportView(CARNET);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 840, 150));

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        eliminarjt.setText("ELIMINAR");
        eliminarjt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarjtActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarjt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 110, 30));

        jButton3.setText("AÑADIR MASCOTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 130, 40));

        JBGUARDAR.setText("GUARDAR");
        JBGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(JBGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, 30));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel8.setText("Direccion:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 40));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel7.setText("Celular:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel6.setText("Apellidos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setText("carnet");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 40));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("PROPIETARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 360, 40));

        MOSTRAR.setText("MOSTRAR");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });
        getContentPane().add(MOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 130, 30));

        JBSELECCIONAR.setText("SELECCIONAR");
        JBSELECCIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSELECCIONARActionPerformed(evt);
            }
        });
        getContentPane().add(JBSELECCIONAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        nuevo.setText("NUEVO");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 100, 30));

        JBLIMPIAR.setText("LIMPIAR");
        JBLIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLIMPIARActionPerformed(evt);
            }
        });
        getContentPane().add(JBLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 90, 30));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("Correo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 90, 30));

        jScrollPane3.setViewportView(correo);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGUARDARActionPerformed
        pro.Insertar(Integer.parseInt(CARNET.getText()), NOMBRE.getText(), APELLIDO.getText(),CELULAR.getText(),correo.getText(), DIRECCION.getText());
        pro.Buscar(jTable1, "");
          Bloquear();
      
        Limpiar();
    }//GEN-LAST:event_JBGUARDARActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      FrameAnimal mascota= new FrameAnimal();
      mascota.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
pro.Buscar(jTable1, "");        // TODO add your handling code here:
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void eliminarjtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarjtActionPerformed
int fmod = jTable1.getSelectedRow();
       
       
         
            pro.Eliminar((int) jTable1.getValueAt(fmod, 0),"","","","","");
            pro.Buscar(jTable1,"");        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarjtActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
      pro.Actualizar(Integer.parseInt(CARNET.getText()),NOMBRE.getText(),APELLIDO.getText(),CELULAR.getText(),DIRECCION.getText(),correo.getText());
      pro.Buscar(jTable1 ,"");
      JOptionPane.showMessageDialog(rootPane, "Los datos se han actualizado con exito");
      nuevo.setEnabled(true);
      
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void JBSELECCIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSELECCIONARActionPerformed
 int fmod = jTable1.getSelectedRow();
       if (fmod >= 0) {
           CARNET.setText(jTable1.getValueAt(fmod, 0).toString());
           NOMBRE.setText(jTable1.getValueAt(fmod, 1).toString());
          APELLIDO.setText(jTable1.getValueAt(fmod, 2).toString());
          CELULAR.setText(jTable1.getValueAt(fmod, 3).toString());
            DIRECCION.setText(jTable1.getValueAt(fmod, 4).toString());
            correo.setText(jTable1.getValueAt(fmod, 5).toString());

        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ");
        }         // TODO add your handling code here:
       Desbloquear();
      JBSELECCIONAR.setEnabled(true);
      eliminarjt.setEnabled(true);
      JBGUARDAR.setEnabled(false);
      nuevo.setEnabled(false);
      MODIFICAR.setEnabled(true);
 
    }//GEN-LAST:event_JBSELECCIONARActionPerformed

    private void JBLIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLIMPIARActionPerformed
Limpiar();
pro.Buscar(jTable1, "");// TODO add your handling code here:
    }//GEN-LAST:event_JBLIMPIARActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
Desbloquear();
        nuevo.setEnabled(true);
        JBGUARDAR.setEnabled(true);
        MODIFICAR.setEnabled(false);
        eliminarjt.setEnabled(false);
        JBLIMPIAR.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane APELLIDO;
    private javax.swing.JTextPane CARNET;
    private javax.swing.JTextPane CELULAR;
    private javax.swing.JTextPane DIRECCION;
    private javax.swing.JButton JBGUARDAR;
    private javax.swing.JButton JBLIMPIAR;
    private javax.swing.JButton JBSELECCIONAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JTextPane NOMBRE;
    private javax.swing.JTextPane correo;
    private javax.swing.JButton eliminarjt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables
}
