/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import proyectoclinica.AtencionDetalle;
import proyectoclinica.AtencionGeneral;
import proyectoclinica.Conexion;
import proyectoclinica.HeaderTable;
import proyectoclinica.Propietario;
import proyectoclinica.asistente;
import proyectoclinica.persona;
import proyectoclinica.servicio;
import proyectoclinica.veterinario;

/**
 *
 * @author Male
 */
public class Frameatencion extends javax.swing.JFrame {

    AtencionGeneral aten;
    persona per;
    Propietario pro;
    servicio ser;
    veterinario vet;
    AtencionDetalle atenc;
    DefaultTableModel model;
    Conexion cnx=new Conexion();
    public Frameatencion() {
       atenc= new AtencionDetalle();
        aten= new AtencionGeneral();
        per=new asistente();
        pro=new Propietario();
        ser=new servicio();
        vet=new veterinario();
        initComponents();
        ser.ListarServicio(comboxservicio);
        vet.ListarVeterinario(comboveterinario);
        per.ListarAsistente(comboasistente);
        this.repintarHeaderTabla();
       this.repintarHeaderTablaaten();
    }
    private void repintarHeaderTabla(){
        JTableHeader jtableHeader = jTable1.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderTable());
        jTable1.setTableHeader(jtableHeader);
    }
       private void repintarHeaderTablaaten(){
        JTableHeader jtableHeader = tableatencion.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderTable());
        tableatencion.setTableHeader(jtableHeader);
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtnroatencion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_idpro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nrohistorial = new javax.swing.JTextField();
        JBGUARDAR = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jttotal = new javax.swing.JTextField();
        comboasistente = new javax.swing.JComboBox<>();
        comboveterinario = new javax.swing.JComboBox<>();
        jt_ci = new javax.swing.JTextField();
        jtnombre = new javax.swing.JTextField();
        comboxservicio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableatencion = new javax.swing.JTable();
        jtprecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(178, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("MOSTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 70)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/login.png"))); // NOI18N
        jLabel2.setText("       ATENCION GENERAL");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1402, 170));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CI PROPIETARIO:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 114, 28));

        jtnroatencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnroatencionActionPerformed(evt);
            }
        });
        jPanel2.add(jtnroatencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 190, 30));

        jLabel3.setText("PRECIO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 124, 32));

        jtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfechaActionPerformed(evt);
            }
        });
        jPanel2.add(jtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 157, 32));

        jLabel4.setText("TOTAL");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 107, -1));

        jLabel5.setText("ID PROPIETARIO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 102, -1));

        jt_idpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_idproActionPerformed(evt);
            }
        });
        jPanel2.add(jt_idpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 190, 33));

        jLabel6.setText("SERVICIO:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 104, 31));

        jLabel7.setText("VETERINARIO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 126, 34));

        jLabel8.setText("ASISTENTE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel9.setText("HISTORIAL CLINICO");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 30));
        jPanel2.add(nrohistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 190, 30));

        JBGUARDAR.setText("GUARDAR");
        JBGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGUARDARActionPerformed(evt);
            }
        });
        jPanel2.add(JBGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 171, 45));

        jButton3.setText("MODIFICAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 710, 171, 49));

        jButton5.setText("ELIMINAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 710, 171, 47));

        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 700, 171, 51));

        jttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttotalActionPerformed(evt);
            }
        });
        jPanel2.add(jttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, 140, 30));

        comboasistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboasistenteActionPerformed(evt);
            }
        });
        jPanel2.add(comboasistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 300, 30));

        comboveterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboveterinarioActionPerformed(evt);
            }
        });
        jPanel2.add(comboveterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 300, 30));

        jt_ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_ciActionPerformed(evt);
            }
        });
        jPanel2.add(jt_ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 190, 30));

        jtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnombreActionPerformed(evt);
            }
        });
        jPanel2.add(jtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 190, 30));

        comboxservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxservicioActionPerformed(evt);
            }
        });
        jPanel2.add(comboxservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 300, 30));

        jLabel10.setText("PROPIETARIO");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 102, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("NRO DE ATENCION");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 114, 28));

        tableatencion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableatencion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 680, 150));

        jtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtprecioActionPerformed(evt);
            }
        });
        jPanel2.add(jtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 690, 120));

        jLabel12.setText("FECHA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 124, 32));

        jButton7.setText("AÑADIR PROPIETARIO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jButton2.setText("SELECCIONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtnroatencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnroatencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnroatencionActionPerformed

    private void jtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfechaActionPerformed

    private void JBGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGUARDARActionPerformed
        aten.Insertar(Integer.parseInt(jtnroatencion.getText()), jtfecha.getText(), Integer.parseInt(jttotal.getText()), comboveterinario.getItemAt(comboveterinario.getSelectedIndex()).getIdpersona(),comboasistente.getItemAt(comboasistente.getSelectedIndex()).getIdpersona(),Integer.parseInt(nrohistorial.getText()));    
       aten.Buscar(tableatencion, ""); 
 this.guardarDetalle();// TODO add your handling code here:
    }//GEN-LAST:event_JBGUARDARActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int fmod = tableatencion.getSelectedRow();
       
       
    
            aten.Eliminar((int) tableatencion.getValueAt(fmod, 0),"",0,0,0,0);
            aten.Buscar(tableatencion,"");    
            atenc.mostrarrdetalle(jTable1, "");// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jt_idproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_idproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_idproActionPerformed

    private void comboasistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboasistenteActionPerformed
    cnx.EjecutarConsulta("SELECT asis.idpersonal,per.nombrepersonal,per.apellidopersonal FROM asistente asis,personal per where asis.idpersonal=per.idpersonal ; ");  // TODO add your handling code here:
    }//GEN-LAST:event_comboasistenteActionPerformed

    private void comboveterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboveterinarioActionPerformed
       cnx.EjecutarConsulta("SELECT vet.idpersonal,per.nombrepersonal,per.apellidopersonal FROM veterinario vet,personal per where vet.idpersonal=per.idpersonal ; ");  // TODO add your handling code here:
    }//GEN-LAST:event_comboveterinarioActionPerformed

    private void jt_ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_ciActionPerformed
     pro.buscarPROPIETARIOPorid( jt_idpro,jt_ci.getText());
     pro.buscarPROPIETARIOnombre(jtnombre, jt_ci.getText());
     pro.buscarNumeroHistorial(nrohistorial, jt_ci.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_jt_ciActionPerformed

    private void jtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnombreActionPerformed

    private void comboxservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxservicioActionPerformed
       cnx.EjecutarConsulta("select* from servicio  ; ");  // TODO add your handling code here:
    }//GEN-LAST:event_comboxservicioActionPerformed

    private void jttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       aten.Buscar(tableatencion, "");
       atenc.mostrarrdetalle(jTable1, "");
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
FramePropietario PRO=new FramePropietario();
PRO.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
aten.Actualizar(Integer.parseInt(jtnroatencion.getText()),jtfecha.getText(),Integer.parseInt(jttotal.getText()),comboveterinario.getItemAt(comboveterinario.getSelectedIndex()).getIdpersona(),comboasistente.getItemAt(comboasistente.getSelectedIndex()).getIdpersona(), Integer.parseInt(nrohistorial.getText()));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtprecioActionPerformed
String precio =jtprecio.getText();   
jttotal.setText(precio);// TODO add your handling code here:
    }//GEN-LAST:event_jtprecioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frameatencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frameatencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frameatencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frameatencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frameatencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGUARDAR;
    public javax.swing.JComboBox<persona> comboasistente;
    public javax.swing.JComboBox<veterinario> comboveterinario;
    public javax.swing.JComboBox<servicio> comboxservicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jt_ci;
    private javax.swing.JTextField jt_idpro;
    private javax.swing.JTextField jtfecha;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JTextField jtnroatencion;
    private javax.swing.JTextField jtprecio;
    private javax.swing.JTextField jttotal;
    private javax.swing.JTextField nrohistorial;
    private javax.swing.JTable tableatencion;
    // End of variables declaration//GEN-END:variables
    private void guardarDetalle() {
                    atenc.Insertar(Integer.parseInt(jtnroatencion.getText()),
                    comboxservicio.getItemAt(comboxservicio.getSelectedIndex()).getCodservicio(),
                    comboxservicio.getItemAt(comboxservicio.getSelectedIndex()).getPrecio()
            );
            
            atenc.guardarAtencionDetalle();
            this.mostrarDetalle();
    }
    
    private void mostrarDetalle(){
     
        atenc.Buscardetalle(jTable1, jtnroatencion.getText());
        
    }


}




