/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import proyectoclinica.Conexion;
import proyectoclinica.HeaderTable;
import proyectoclinica.servicio;

/**
 *
 * @author Male
 */

public class FrameServicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameServicio
     */
    servicio ser;
    DefaultTableModel model;
    Conexion cnx=new Conexion();
    public FrameServicio() {
        initComponents();
        ser= new servicio();
        this.repintarHeaderTabla();
            
        
    }
    private void repintarHeaderTabla(){
        JTableHeader jtableHeader = jTable1.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderTable());
        jTable1.setTableHeader(jtableHeader);
    }
     public void Limpiar ()
    {            
         jTextFieldcod.setText("");
        jTextFielddescripcion.setText("");
        jTextFieldprecio.setText("");
    }
    
     public void Bloquear()
    {
        jTextFieldcod.setEnabled(false);
        jTextFielddescripcion.setEnabled(false);
        jTextFieldprecio.setEnabled(false);
    }
     public void Desbloquear ()
    {
        jTextFieldcod.setEnabled(true);
        jTextFielddescripcion.setEnabled(true);
        jTextFieldprecio.setEnabled(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBnuevo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelcod = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFielddescripcion = new javax.swing.JTextField();
        jTextFieldcod = new javax.swing.JTextField();
        jTextFieldprecio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        JBMOSTRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("BUSCAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 110, 30));

        jBsalir.setText("SALIR");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 100, 30));

        jBeliminar.setText("ELMINAR");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 120, 30));

        jBmodificar.setText("MODIFICAR");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 120, 30));

        jBguardar.setText("GUARDAR");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 120, 30));

        jBnuevo.setText("NUEVO");
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 540, 190));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel5.setText("PRECIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel4.setText("DESCRIPCION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 20));

        jLabelcod.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabelcod.setText("CODIGO ");
        getContentPane().add(jLabelcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setText("SERVICIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 220, -1));
        getContentPane().add(jTextFielddescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, 30));
        getContentPane().add(jTextFieldcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 160, 30));
        getContentPane().add(jTextFieldprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 170, 30));

        jButton1.setText("SELECCCIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        JBMOSTRAR.setText("MOSTRAR");
        JBMOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMOSTRARActionPerformed(evt);
            }
        });
        getContentPane().add(JBMOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
        ser.Insertarservicio(Integer.parseInt(jTextFieldcod.getText()), jTextFielddescripcion.getText(),Integer.parseInt(jTextFieldprecio.getText()));
      ser.Buscar(jTable1 ,"");
        
      Limpiar();
      jBguardar.setEnabled(false);
      jBmodificar.setEnabled(false);
      jBnuevo.setEnabled(true);
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
          ser.Actualizar(Integer.parseInt(jTextFieldcod.getText()),jTextFielddescripcion.getText(),Integer.parseInt(jTextFieldprecio.getText()));
       ser.Buscar(jTable1,"");

       JOptionPane.showMessageDialog(rootPane, "Los datos se han actualizado con exito");
       Bloquear();
       Limpiar();
       ser.Buscar(jTable1, "");
       jBnuevo.setEnabled(true);
    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
        ser.Eliminarservicio(Integer.parseInt(jTextFieldcod.getText()),jTextFielddescripcion.getText(), Integer.parseInt(jTextFieldprecio.getText()));
        ser.Buscar(jTable1,"");

        JOptionPane.showMessageDialog(rootPane, "Los datos se han ELIMINADO con exito");
        Bloquear();
        Limpiar();
   
        jBguardar.setEnabled(false);
        jBmodificar.setEnabled(false);
        jBnuevo.setEnabled(true);
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
          Desbloquear();
        jBnuevo.setEnabled(true);
        jBguardar.setEnabled(true);
        jBmodificar.setEnabled(false);
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ser.BuscarIDser(jTable1,jTextFieldcod.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Desbloquear();
       jBnuevo.setEnabled(false);
       jBguardar.setEnabled(false);
       jBmodificar.setEnabled(true);
       jBeliminar.setEnabled(true);
       int fmod = jTable1.getSelectedRow();
       if (fmod >= 0) {
           jTextFieldcod.setText(jTable1.getValueAt(fmod, 0).toString());
           jTextFielddescripcion.setText(jTable1.getValueAt(fmod, 1).toString());
           jTextFieldprecio.setText(jTable1.getValueAt(fmod, 2).toString());
           
            
        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBMOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMOSTRARActionPerformed
ser.Buscar(jTable1, "");        // TODO add your handling code here:
    }//GEN-LAST:event_JBMOSTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBMOSTRAR;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JButton jBsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelcod;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldcod;
    private javax.swing.JTextField jTextFielddescripcion;
    private javax.swing.JTextField jTextFieldprecio;
    // End of variables declaration//GEN-END:variables
}
